import type { Category } from "./types";

export const VIRTUAL_FAVORIS: Category = {
  id: "cat-favoris",
  name: "Favoris",
  icon: "Star",
  color: "mist",
  phrases: [],
  virtual: "favoris",
};

export const VIRTUAL_RECENTS: Category = {
  id: "cat-recents",
  name: "Récents",
  icon: "History",
  color: "mist",
  phrases: [],
  virtual: "recents",
};

export const DEFAULT_CATEGORIES: Category[] = [
  {
    id: "cat-conversation",
    name: "Conversation",
    icon: "MessageCircle",
    color: "mist",
    phrases: [
      { id: "p-bonjour", label: "Bonjour" },
      { id: "p-bonsoir", label: "Bonsoir" },
      { id: "p-bonne-journee", label: "Bonne journée." },
      { id: "p-bonne-nuit", label: "Bonne nuit." },
      { id: "p-comment-ca-va", label: "Comment ça va?" },
      { id: "p-ca-va-bien", label: "Ça va bien." },
      { id: "p-ca-va-pas", label: "Ça ne va pas bien." },
      { id: "p-comment-tappelles", label: "Comment tu t'appelles?" },
      { id: "p-ravi", label: "Ravi de vous voir." },
      { id: "p-excusez", label: "Excusez-moi." },
      { id: "p-attendez", label: "Attendez un instant." },
      { id: "p-bonne-journee-q", label: "As-tu passé une bonne journée?" },
      { id: "p-bienvenue", label: "Bienvenue." },
      { id: "p-quoi-neuf", label: "Quoi de neuf?" },
      { id: "p-repete", label: "Je n'ai pas compris, pouvez-vous répéter?" },
      { id: "p-aider", label: "Pourriez-vous m'aider?" },
      { id: "p-peux-avoir", label: "Est-ce que je peux avoir" },
      { id: "p-plaisir", label: "Ça m'a fait plaisir." },
      { id: "p-jaime", label: "Je l'aime." },
      { id: "p-jaime-pas", label: "Je n'aime pas ça." },
      { id: "p-a-plus-tard", label: "À plus tard." },
      { id: "p-au-revoir", label: "Au revoir." },
      { id: "p-oui", label: "Oui" },
      { id: "p-non", label: "Non" },
      { id: "p-peut-etre", label: "Peut-être" },
    ],
  },
  {
    id: "cat-informations",
    name: "Informations",
    icon: "BadgeInfo",
    color: "mist",
    phrases: [
      { id: "p-je-mappelle", label: "Je m'appelle" },
      { id: "p-jai", label: "J'ai" },
      { id: "p-je-suis", label: "Je suis" },
      { id: "p-je-veux", label: "Je veux" },
      { id: "p-je-voudrais", label: "Je voudrais" },
      { id: "p-jhabite", label: "J'habite à" },
      { id: "p-mon-nom", label: "Mon nom est" },
      { id: "p-mon-numero", label: "Mon numéro de téléphone est" },
      { id: "p-aujourdhui", label: "Aujourd'hui" },
      { id: "p-demain", label: "Demain" },
      { id: "p-hier", label: "Hier" },
      { id: "p-merci", label: "Merci." },
      { id: "p-merci-bcp", label: "Merci beaucoup." },
      { id: "p-sil-vous-plait", label: "S'il vous plaît." },
      { id: "p-de-rien", label: "De rien." },
      { id: "p-daccord", label: "D'accord." },
      { id: "p-je-sais-pas", label: "Je ne sais pas." },
      { id: "p-je-comprends", label: "Je comprends." },
      { id: "p-je-comprends-pas", label: "Je ne comprends pas." },
      { id: "p-lentement", label: "Parlez plus lentement." },
    ],
  },
  {
    id: "cat-personnes",
    name: "Personnes",
    icon: "Users",
    color: "mist",
    phrases: [
      { id: "p-moi", label: "Moi" },
      { id: "p-toi", label: "Toi" },
      { id: "p-lui", label: "Lui" },
      { id: "p-elle", label: "Elle" },
      { id: "p-nous", label: "Nous" },
      { id: "p-vous", label: "Vous" },
      { id: "p-maman", label: "Maman" },
      { id: "p-papa", label: "Papa" },
      { id: "p-famille", label: "Ma famille" },
      { id: "p-ami", label: "Un ami" },
      { id: "p-amie", label: "Une amie" },
      { id: "p-medecin", label: "Le médecin" },
      { id: "p-infirmiere", label: "L'infirmière" },
      { id: "p-voisin", label: "Le voisin" },
      { id: "p-enseignant", label: "L'enseignant" },
      { id: "p-qui-est", label: "Qui est-ce?" },
      { id: "p-cest-qui", label: "C'est qui?" },
      { id: "p-avec-toi", label: "Avec toi" },
      { id: "p-tout-seul", label: "Tout seul" },
      { id: "p-quelquun", label: "Quelqu'un" },
    ],
  },
  {
    id: "cat-endroits",
    name: "Endroits",
    icon: "MapPin",
    color: "mist",
    phrases: [
      { id: "p-a-la-maison", label: "À la maison" },
      { id: "p-dehors", label: "Dehors" },
      { id: "p-ecole", label: "À l'école" },
      { id: "p-magasin", label: "Au magasin" },
      { id: "p-hopital", label: "À l'hôpital" },
      { id: "p-chez-medecin", label: "Chez le médecin" },
      { id: "p-restaurant", label: "Au restaurant" },
      { id: "p-parc", label: "Au parc" },
      { id: "p-voiture", label: "Dans la voiture" },
      { id: "p-travail", label: "Au travail" },
      { id: "p-ou-sommes", label: "Où sommes-nous?" },
      { id: "p-ou-allons", label: "Où allons-nous?" },
      { id: "p-rentrer", label: "Je voudrais rentrer." },
      { id: "p-ici", label: "Ici" },
      { id: "p-la-bas", label: "Là-bas" },
      { id: "p-etage", label: "À l'étage" },
      { id: "p-dehors-sv", label: "Je veux aller dehors." },
      { id: "p-visite", label: "En visite" },
    ],
  },
  {
    id: "cat-maison",
    name: "Maison",
    icon: "House",
    color: "mist",
    phrases: [
      { id: "p-chambre", label: "La chambre" },
      { id: "p-salon", label: "Le salon" },
      { id: "p-cuisine", label: "La cuisine" },
      { id: "p-sdb", label: "La salle de bain" },
      { id: "p-toilettes", label: "Les toilettes" },
      { id: "p-jardin", label: "Le jardin" },
      { id: "p-lumiere-on", label: "Allumez la lumière." },
      { id: "p-lumiere-off", label: "Éteignez la lumière." },
      { id: "p-tele-on", label: "Allumez la télé." },
      { id: "p-tele-off", label: "Éteignez la télé." },
      { id: "p-fenetre", label: "Ouvrez la fenêtre." },
      { id: "p-porte", label: "Fermez la porte." },
      { id: "p-couverture", label: "La couverture" },
      { id: "p-oreiller", label: "L'oreiller" },
      { id: "p-lit", label: "Le lit" },
      { id: "p-chaise", label: "La chaise" },
      { id: "p-table", label: "La table" },
      { id: "p-canape", label: "Le canapé" },
    ],
  },
  {
    id: "cat-nourriture",
    name: "Nourriture",
    icon: "Utensils",
    color: "mist",
    phrases: [
      { id: "p-jai-faim", label: "J'ai faim." },
      { id: "p-jai-soif", label: "J'ai soif." },
      { id: "p-eau", label: "De l'eau" },
      { id: "p-cafe", label: "Un café" },
      { id: "p-the", label: "Un thé" },
      { id: "p-jus", label: "Un jus" },
      { id: "p-lait", label: "Du lait" },
      { id: "p-pain", label: "Du pain" },
      { id: "p-fromage", label: "Du fromage" },
      { id: "p-viande", label: "De la viande" },
      { id: "p-poisson", label: "Du poisson" },
      { id: "p-legumes", label: "Des légumes" },
      { id: "p-fruits", label: "Des fruits" },
      { id: "p-soupe", label: "De la soupe" },
      { id: "p-dessert", label: "Un dessert" },
      { id: "p-petit-dej", label: "Le petit-déjeuner" },
      { id: "p-dejeuner", label: "Le déjeuner" },
      { id: "p-diner", label: "Le dîner" },
      { id: "p-cest-bon", label: "C'est bon." },
      { id: "p-cest-chaud", label: "C'est trop chaud." },
      { id: "p-encore", label: "Encore." },
      { id: "p-cest-tout", label: "C'est suffisant." },
    ],
  },
  {
    id: "cat-objets",
    name: "Objets",
    icon: "Box",
    color: "mist",
    phrases: [
      { id: "p-telephone", label: "Mon téléphone" },
      { id: "p-lunettes", label: "Mes lunettes" },
      { id: "p-cles", label: "Mes clés" },
      { id: "p-sac", label: "Mon sac" },
      { id: "p-livre", label: "Un livre" },
      { id: "p-stylo", label: "Un stylo" },
      { id: "p-papier", label: "Du papier" },
      { id: "p-telecommande", label: "La télécommande" },
      { id: "p-ordinateur", label: "L'ordinateur" },
      { id: "p-chargeur", label: "Le chargeur" },
      { id: "p-montre", label: "Ma montre" },
      { id: "p-argent", label: "De l'argent" },
      { id: "p-carte", label: "Ma carte" },
      { id: "p-serviette", label: "Une serviette" },
      { id: "p-verre", label: "Un verre" },
      { id: "p-assiette", label: "Une assiette" },
      { id: "p-cuillere", label: "Une cuillère" },
      { id: "p-fourchette", label: "Une fourchette" },
    ],
  },
  {
    id: "cat-sentiment",
    name: "Sentiment",
    icon: "Heart",
    color: "mist",
    phrases: [
      { id: "p-content", label: "Je suis content." },
      { id: "p-contente", label: "Je suis contente." },
      { id: "p-triste", label: "Je suis triste." },
      { id: "p-colere", label: "Je suis en colère." },
      { id: "p-peur", label: "J'ai peur." },
      { id: "p-fatigue", label: "Je suis fatigué." },
      { id: "p-fatiguee", label: "Je suis fatiguée." },
      { id: "p-ennuie", label: "Je m'ennuie." },
      { id: "p-inquiet", label: "Je suis inquiet." },
      { id: "p-bien", label: "Je me sens bien." },
      { id: "p-mal", label: "Je me sens mal." },
      { id: "p-aime-ca", label: "J'aime ça." },
      { id: "p-naime-pas", label: "Je n'aime pas ça." },
      { id: "p-je-taime", label: "Je t'aime." },
      { id: "p-ca-va-pas-moi", label: "Ça ne va pas." },
      { id: "p-heureux", label: "Je suis heureux." },
      { id: "p-decu", label: "Je suis déçu." },
      { id: "p-calme", label: "J'ai besoin de calme." },
    ],
  },
  {
    id: "cat-corps",
    name: "Corps",
    icon: "HeartPulse",
    color: "mist",
    phrases: [
      { id: "p-tete", label: "La tête" },
      { id: "p-ventre", label: "Le ventre" },
      { id: "p-dos", label: "Le dos" },
      { id: "p-gorge", label: "La gorge" },
      { id: "p-main", label: "La main" },
      { id: "p-pied", label: "Le pied" },
      { id: "p-jambe", label: "La jambe" },
      { id: "p-bras", label: "Le bras" },
      { id: "p-yeux", label: "Les yeux" },
      { id: "p-oreilles", label: "Les oreilles" },
      { id: "p-mal-tete", label: "J'ai mal à la tête." },
      { id: "p-mal-ventre", label: "J'ai mal au ventre." },
      { id: "p-mal-dos", label: "J'ai mal au dos." },
      { id: "p-mal-gorge", label: "J'ai mal à la gorge." },
      { id: "p-jai-mal", label: "J'ai mal." },
      { id: "p-froid", label: "J'ai froid." },
      { id: "p-chaud", label: "J'ai chaud." },
      { id: "p-toilettes-besoin", label: "J'ai besoin d'aller aux toilettes." },
    ],
  },
  {
    id: "cat-vetements",
    name: "Vêtements",
    icon: "Shirt",
    color: "mist",
    phrases: [
      { id: "p-pull", label: "Un pull" },
      { id: "p-tshirt", label: "Un t-shirt" },
      { id: "p-pantalon", label: "Un pantalon" },
      { id: "p-jupe", label: "Une jupe" },
      { id: "p-robe", label: "Une robe" },
      { id: "p-manteau", label: "Un manteau" },
      { id: "p-veste", label: "Une veste" },
      { id: "p-chaussures", label: "Des chaussures" },
      { id: "p-chaussettes", label: "Des chaussettes" },
      { id: "p-bonnet", label: "Un bonnet" },
      { id: "p-echarpe", label: "Une écharpe" },
      { id: "p-gants", label: "Des gants" },
      { id: "p-pyjama", label: "Le pyjama" },
      { id: "p-lunettes-soleil", label: "Les lunettes de soleil" },
      { id: "p-mettre", label: "Je veux mettre" },
      { id: "p-enlever", label: "Enlevez" },
      { id: "p-trop-serre", label: "C'est trop serré." },
      { id: "p-jai-froid-vet", label: "J'ai froid, un pull s'il vous plaît." },
    ],
  },
  {
    id: "cat-temps",
    name: "Temps",
    icon: "Clock",
    color: "mist",
    phrases: [
      { id: "p-maintenant", label: "Maintenant" },
      { id: "p-plus-tard", label: "Plus tard" },
      { id: "p-tout-de-suite", label: "Tout de suite" },
      { id: "p-matin", label: "Le matin" },
      { id: "p-apres-midi", label: "L'après-midi" },
      { id: "p-soir", label: "Le soir" },
      { id: "p-nuit", label: "La nuit" },
      { id: "p-semaine", label: "Cette semaine" },
      { id: "p-weekend", label: "Le week-end" },
      { id: "p-attendre", label: "Attendez un moment." },
      { id: "p-plus-vite", label: "Plus vite" },
      { id: "p-plus-lent", label: "Plus lentement" },
      { id: "p-quelle-heure", label: "Quelle heure est-il?" },
      { id: "p-combien-temps", label: "Combien de temps?" },
    ],
  },
  {
    id: "cat-questions",
    name: "Questions",
    icon: "CircleHelp",
    color: "mist",
    phrases: [
      { id: "p-comment", label: "Comment?" },
      { id: "p-pourquoi", label: "Pourquoi?" },
      { id: "p-quand", label: "Quand?" },
      { id: "p-ou", label: "Où?" },
      { id: "p-qui", label: "Qui?" },
      { id: "p-combien", label: "Combien?" },
      { id: "p-questce", label: "Qu'est-ce que c'est?" },
      { id: "p-cest-ou", label: "C'est où?" },
      { id: "p-on-fait-quoi", label: "Qu'est-ce qu'on fait?" },
      { id: "p-pouvez-expliquer", label: "Pouvez-vous m'expliquer?" },
      { id: "p-cest-pour-quand", label: "C'est pour quand?" },
      { id: "p-cest-a-qui", label: "C'est à qui?" },
    ],
  },
];

export function allDefaultCategories(): Category[] {
  return [...DEFAULT_CATEGORIES, VIRTUAL_FAVORIS, VIRTUAL_RECENTS];
}
