import { BASE_DARK, BASE_LIGHT } from "../palette";
import type { ThemeDef } from "../types";

/** Built-in ClairVoix appearance (what the app looked like before theming). */
export const DEFAULT_THEMES: ThemeDef[] = [
  {
    id: "clairvoix",
    name: "ClairVoix (défaut)",
    cat: "default",
    emoji: "💬",
    era: "Standard",
    decor: "soft",
    palettes: {
      light: { ...BASE_LIGHT, tiles: "light" },
      dark: { ...BASE_DARK, tiles: "dark" },
    },
  },
  {
    id: "clairvoix-pastel",
    name: "ClairVoix Pastel",
    cat: "default",
    emoji: "🌸",
    era: "Doux",
    decor: "soft",
    radius: [10, 12, 14, 16, 20, 24],
    palettes: {
      light: {
        bg: "#e8e2f0",
        chrome: "#f3eef8",
        chrome2: "#ddd3ec",
        chromeSel: "#c8b8e2",
        surface: "#fffdfe",
        surface2: "#f3ecf8",
        pred: "#e4dbee",
        ink: "#33224a",
        muted: "#5a4870",
        subtle: "#8a7a9c",
        line: "#d4c4e4",
        lineStrong: "#a890bc",
        accent: "#9c6bd8",
        accentHover: "#8a54c8",
        accentFg: "#ffffff",
        accentSoft: "#ecddfa",
        accentSoftFg: "#5c2a9a",
        info: "#6f9ce0",
        infoSoft: "#dfe9f8",
        pos: "#6fae8a",
        posSoft: "#e0efe6",
        danger: "#e07a8a",
        dangerSoft: "#fce0e4",
        dangerFg: "#a03a4a",
        scrim: "rgb(51 34 74 / 0.35)",
        tiles: "pastel",
      },
      dark: {
        bg: "#241a30",
        chrome: "#33284a",
        chrome2: "#2a1f3c",
        chromeSel: "#4a3c62",
        surface: "#2f2440",
        surface2: "#3a2e50",
        pred: "#1e1628",
        ink: "#f4eefe",
        muted: "#d6cce4",
        subtle: "#9a8eb0",
        line: "#4c3c66",
        lineStrong: "#6e5c90",
        accent: "#b99aec",
        accentSoft: "#3f2a60",
        accentSoftFg: "#e4d2fa",
        tiles: "dark",
      },
    },
  },
];
